language: php

dist: precise

sudo: false

php:
  - 5.6
  - 7.0
  - 7.1

env:
  - DB=SQLITE CORE_RELEASE=4 PDO=1

matrix:
  fast_finish: true
  include:
    - php: 5.6
      env: DB=SQLITE CORE_RELEASE=4 PDO=0

before_script:
  # Init PHP
  - printf "\n" | pecl install imagick
  - phpenv rehash
  - phpenv config-rm xdebug.ini
  - echo 'memory_limit = 2048M' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

# Install composer dependencies
  - composer validate
  - composer require symfony/config:^3.2 silverstripe/framework:4.0.x-dev silverstripe/cms:4.0.x-dev silverstripe/siteconfig:4.0.x-dev silverstripe/config:1.0.x-dev silverstripe/admin:1.0.x-dev silverstripe/assets:1.0.x-dev silverstripe/versioned:1.0.x-dev --no-update
  - composer install --prefer-dist --no-interaction --no-progress --no-suggest --optimize-autoloader --verbose --profile

script:
  - vendor/bin/phpunit vendor/silverstripe/framework/tests
